### ISSUE TITLE
NameError: name 'group_id' is not defined

### ISSUE THREAD

**Issue by AnAnonymousWalrus** [Avnsx/fansly#11]
Getting the below error when running the standalone executable. Running the application on a Windows 10 Virtual Machine in the root of the drive I am saving the data to's directory. Tried running as admin, compatibility mode, etc, did I miss a prerequisite download or something?

 Info | 15:30 || Creating download directories ...
Traceback (most recent call last):
  File "fansly_scraper.py", line 234, in <module>
NameError: name 'group_id' is not defined
[6680] Failed to execute script 'fansly_scraper' due to unhandled exception!

**Comment by Avnsx** [comment]
> Getting the below error when running the standalone executable. Running the application on a Windows 10 Virtual Machine in the root of the drive I am saving the data to's directory. Tried running as admin, compatibility mode, etc, did I miss a prerequisite download or something?
> 
> Info | 15:30 || Creating download directories ... Traceback (most recent call last): File "fansly_scraper.py", line 234, in NameError: name 'group_id' is not defined [6680] Failed to execute script 'fansly_scraper' due to unhandled exception!

No, this is an issue with downloading content from messages. In the code I wrote setting group id to None after trying to loop over a couple messages.     https://github.com/Avnsx/fansly/blob/b7ab00d376e2537640b99ca613c9521f3def2003/fansly_scraper.py#L232

I did not test this thesis yet, but this most likely happend, because you created a entirely new fansly account which has not received a single message (not even any automated message) from any creator at all, which caused the variable to never get set to None & instead just don't exist and when line 234 tried to interact with a unset variable it just crashed due to a NameError.

You can fix this temporarily by following a couple creators until one of them messages you, I'll publish an update soon which fixes a couple bugs including this one.

**Comment by Avnsx** [comment]
Update verified my thesis, I was correct. I fixed it in my developer verison. Will soon publish update

**Comment by Avnsx** [comment]
Fixed with version 0.3.1

You can use the updater.exe, to comfortably update to the newest version
