### ISSUE TITLE
macOS 13.1 : pyexiv2 only supports these Python versions: ['3.5', '3.6', '3.7', '3.8', '3.9']

### ISSUE THREAD

**Issue by baszero** [Avnsx/fansly#168]
Because Pyton 3.12 had a severe issue with a library called nympo, I installed Python 3.11.

No I get this error:

```
Traceback (most recent call last):
  File "/Users/me/Documents/fansly-downloader-master/fansly_downloader.py", line 15, in <module>
    from utils.metadata_manager import MetadataManager
  File "/Users/me/Documents/fansly-downloader-master/utils/metadata_manager.py", line 1, in <module>
    import pyexiv2
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyexiv2/__init__.py", line 6, in <module>
    from .core import *
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyexiv2/core.py", line 1, in <module>
    from .lib import exiv2api
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyexiv2/lib/__init__.py", line 14, in <module>
    raise RuntimeError('pyexiv2 only supports these Python versions: {} . But your version is {} .'.format(expected_py_version, py_version))
RuntimeError: pyexiv2 only supports these Python versions: ['3.5', '3.6', '3.7', '3.8', '3.9'] . But your version is 3.1 .
```

**Comment by c240amg** [comment]
This is probably because the version check only uses the first digit after the full stop, rather than doing a integer check. I don't think it's a fansly_download issue, but a pyexiv2 issue...

**Comment by c240amg** [comment]
Have edited the file and got past this error. you need to change this file (note I am using a virtual environment):
`/fansly-downloader/venv/lib/python3.11/site-packages/pyexiv2/lib/__init__.py`
and add
`expected_py_version = ['3.5', '3.6', '3.7', '3.8', '3.9', '3.1']`
After this, you do get a different error, which I am trying to debug...
`/fansly-downloader/venv/lib/python3.11/site-packages/pyexiv2/lib/libexiv2.dylib' (no such file)`

**Comment by neiljohn150** [comment]
@c240amg I created a workaround to run without pyexiv2 for MacOS https://github.com/Avnsx/fansly-downloader/commit/59d60d23d36be7e5c7930afe5755e906d733fac6
