### ISSUE TITLE
Problem with downloading m3u8 videos

### ISSUE THREAD

**Issue by AlexMariacio** [Avnsx/fansly#171]
Tried to download quite recent (from 20.10.2023) content pics and gifs works well, but videos don't. Although some older posts with m3u8 videos were downloadable.
So after trying to download - i got this:

Traceback (most recent call last):
File "fansly_downloader.py", line 1189, in <module>
File "fansly_downloader.py", line 744, in sort_download 
File "fansly_downloader.py", line 618, in download_m3u8
IndexError: tuple index out of range.

Please help.

**Comment by AlexMariacio** [comment]
*File "fansly_downloader.py", line 1189, in <module>

**Comment by AlexMariacio** [comment]
*File "fansly_downloader.py", line 1189, in < module >

**Comment by alexeyrubenoff** [comment]
I think this happens with videos that don't have an audio track - when i changed the line
`audio_stream = input_container.streams.audio[0]`
to
`audio_stream = input_container.streams.video[0]`

the download succeeded.

**Comment by AlexMariacio** [comment]
> I think this happens with videos that don't have an audio track - when i changed the line `audio_stream = input_container.streams.audio[0]` to `audio_stream = input_container.streams.video[0]`
> 
> the download succeeded.

Thank you very much for the answer, but where you change this line? There is no file except "config" where you can change settings.

**Comment by Darihx** [comment]
> I think this happens with videos that don't have an audio track - when i changed the line `audio_stream = input_container.streams.audio[0]` to `audio_stream = input_container.streams.video[0]`
> 
> the download succeeded.

I did this but now all the videos are downloaded without sound xd
