### ISSUE TITLE
Error 19 when downloading videos_m3u8

### ISSUE THREAD

**Issue by Melonyz** [Avnsx/fansly#173]
Been happening recently and the programs skips out on a lot of files after.
 
 [19]ERROR | 12:54 || Unexpected error during sorting Single Post download;
Traceback (most recent call last):
  File "fansly_downloader.py", line 1189, in <module>
  File "fansly_downloader.py", line 744, in sort_download
  File "fansly_downloader.py", line 618, in download_m3u8
IndexError: tuple index out of range
![image_2023-10-24_130131952](https://github.com/Avnsx/fansly-downloader/assets/148841381/8612b3fc-57a5-444d-a1b6-faf4f10da94f)

**Comment by z6mbie** [comment]
I have this problem as well. Have u found any fixes?

**Comment by LeonRoyal** [comment]
Same exact issue, mine is just called Error [33]

**Comment by RalkeyOfficial** [comment]
@Melonyz @LeonRoyal @z6mbie Im planning on attempting to recreate this error later,
could you tell me a bit of information regarding the issue?

1) what version of the downloader do you use?
2) did you dowload the source code from the Releases tab or from the latest version on `master` branch?
3) what creator did you attempt to download from?

**Comment by Melonyz** [comment]
@RalkeyOfficial v0.4.1, master branch and tinytvoya

**Comment by prxststr** [comment]
Yes, same issue.

**Comment by alexeyrubenoff** [comment]
I think this happens with videos that don't have an audio track - when i changed the line
`audio_stream = input_container.streams.audio[0]`
to
`audio_stream = input_container.streams.video[0]` 

the download succeeded.

**Comment by prxststr** [comment]
> I think this happens with videos that don't have an audio track - when i changed the line `audio_stream = input_container.streams.audio[0]` to `audio_stream = input_container.streams.video[0]`
> 
> the download succeeded.

Hi!

The problem solved here.
https://github.com/prof79/fansly-downloader-ng/issues/2
