### ISSUE TITLE
Unexpected Error during Sorting

### ISSUE THREAD

**Issue by IBananaShake** [Avnsx/fansly#174]
I get this error when trying to download newer posts.

 [19]ERROR | 22:15 || Unexpected error during sorting Single Post download;
Traceback (most recent call last):
  File "fansly_downloader.py", line 1189, in <module>
  File "fansly_downloader.py", line 744, in sort_download
  File "fansly_downloader.py", line 618, in download_m3u8
IndexError: tuple index out of range

The downloader can still download older posts, but newer timeline and message posts are just not being downloaded, not even when trying to download single pics / videos

**Comment by Darihx** [comment]
I also have this problem
I tried with all the download modes and this error always occurs at a some point

**Comment by fanRipper** [comment]
having same issue. only new posts like you stated. anybody find a solution yet?

**Comment by CoNayru** [comment]
I have also run into this issue using 0.4.1, it is specifically for videos using "timeline."

**Comment by swuckt** [comment]
https://github.com/Avnsx/fansly-downloader/issues/173#issuecomment-1817826148

**IndexError: tuple index out of range** is an issue where the downloader tries to access audio on _videos with no audio_

If you follow the link, this problem has been addressed in the -ng fork by prof79

https://github.com/prof79/fansly-downloader-ng/issues/2

https://github.com/prof79/fansly-downloader-ng/releases
