### ISSUE TITLE
Not able to install requirements (using master one)

### ISSUE THREAD

**Issue by ghost** [Avnsx/fansly#175]
![Screenshot 2023-11-06 015136](https://github.com/Avnsx/fansly-downloader/assets/149970309/a5722a91-82b0-4824-967f-35a264583588)

**Comment by melithine** [comment]
Can you post the full log rather than just the tail end? A text file attachment would also be much easier to follow than a screenshot.

**Comment by ghost** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\risha\Downloads\Compressed\fansly-downloader-master> pip3 install --user -r requirements.txt
Requirement already satisfied: requests>=2.26.0 in c:\users\risha\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (2.31.0)
Collecting loguru>=0.5.3 (from -r requirements.txt (line 2))
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting imagehash>=4.2.1 (from -r requirements.txt (line 3))
  Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Collecting pillow>=8.4.0 (from -r requirements.txt (line 4))
  Using cached Pillow-10.1.0-cp312-cp312-win_amd64.whl.metadata (9.6 kB)
Collecting python-dateutil>=2.8.2 (from -r requirements.txt (line 5))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting plyvel-ci>=1.5.0 (from -r requirements.txt (line 6))
  Using cached plyvel-ci-1.5.0.tar.gz (36 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting psutil>=5.9.0 (from -r requirements.txt (line 7))
  Using cached psutil-5.9.6-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting av>=9.0.0 (from -r requirements.txt (line 8))
  Downloading av-11.0.0-cp312-cp312-win_amd64.whl.metadata (4.7 kB)
Collecting m3u8>=3.0.0 (from -r requirements.txt (line 9))
  Downloading m3u8-3.6.0-py3-none-any.whl.metadata (15 kB)
Collecting rich>=13.0.0 (from -r requirements.txt (line 10))
  Downloading rich-13.6.0-py3-none-any.whl.metadata (18 kB)
Collecting mutagen>=1.46.0 (from -r requirements.txt (line 11))
  Downloading mutagen-1.47.0-py3-none-any.whl.metadata (1.7 kB)
Collecting pyexiv2>=2.8.2 (from -r requirements.txt (line 12))
  Downloading pyexiv2-2.8.3-cp312-none-win_amd64.whl.metadata (2.9 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\risha\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.26.0->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\risha\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.26.0->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\risha\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.26.0->-r requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\risha\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.26.0->-r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: colorama>=0.3.4 in c:\users\risha\appdata\roaming\python\python312\site-packages (from loguru>=0.5.3->-r requirements.txt (line 2)) (0.4.6)
Collecting win32-setctime>=1.0.0 (from loguru>=0.5.3->-r requirements.txt (line 2))
  Downloading win32_setctime-1.1.0-py3-none-any.whl (3.6 kB)
Collecting PyWavelets (from imagehash>=4.2.1->-r requirements.txt (line 3))
  Downloading PyWavelets-1.4.1.tar.gz (4.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 2.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\risha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\risha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\risha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\risha\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\risha\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\risha\AppData\Local\Temp\pip-build-env-yk55y6f_\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\risha\AppData\Local\Temp\pip-build-env-yk55y6f_\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\risha\AppData\Local\Temp\pip-build-env-yk55y6f_\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\risha\Downloads\Compressed\fansly-downloader-master>

**Comment by ghost** [comment]
[Windows PowerShell.txt](https://github.com/Avnsx/fansly-downloader/files/13326828/Windows.PowerShell.txt)
